export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/SuperRooInc/SuperRoo",
	GITHUB_DISCUSSIONS: "https://github.com/SuperRooInc/SuperRoo/discussions",
	DISCORD: "https://discord.gg/superroo",
	REDDIT: "https://reddit.com/r/SuperRoo",
	X: "https://x.com/superroo",
	LINKEDIN: "https://www.linkedin.com/company/superroo",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/superroo.bsky.social",
	YOUTUBE: "https://www.youtube.com/@SuperRooYT",
	DOCUMENTATION: "https://docs.superroo.com",
	SLACK_DOCS: "https://docs.superroo.com/superroo-cloud/slack-integration",
	CAREERS: "https://careers.superroo.com",
	ISSUES: "https://github.com/SuperRooInc/SuperRoo/issues",
	FEATURE_REQUESTS: "https://github.com/SuperRooInc/SuperRoo/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/SuperRooInc/SuperRoo/discussions",
	CHANGELOG: "https://github.com/SuperRooInc/SuperRoo/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/SuperRooInc/SuperRoo/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.superroo.com/community",
	TUTORIALS: "https://docs.superroo.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=SuperRoo.superroo",
	SECURITY: "https://trust.superroo.com",
	EVALS: "https://superroo.com/evals",
	BLOG_SUBSTACK: "https://blog.superroo.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@SuperRooYT/podcasts",
	FAQ: "https://superroo.com/#faq",
	TESTIMONIALS: "https://superroo.com/#testimonials",
	CLOUD_APP_LOGIN: "https://app.superroo.com/sign-in",
	CLOUD_APP_SIGNUP: "https://app.superroo.com/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.superroo.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.superroo.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.superroo.com/checkout/team",
	SUPPORT: "mailto:support@superroo.com",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
